# Pull the base image
FROM node:alpine

# Set the working directory
WORKDIR /app

# Add the node modules to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Install dependencies
COPY package.json ./

COPY package-lock.json ./

RUN npm install

# Add app
COPY . ./

# Start app
CMD ["npm", "start"]